services:
  - type: web
    name: facial-recog-python-service
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn face_verifire:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    plan: free
